---
title: "Distances and standardization (scaling)"
output: html_notebook
---



```{r}
rm(list=ls())
options(digits = 5)
X <- c(200, 2, 1002, 5)
Y <- c(89, 5, 2500, 5000)
df <- data.frame(X=X, Y=Y)
plot(df, bg="lightgreen", pch=21, xlim=c(0,1020), main="Plot with raw data")
text(X, Y, pos=4, labels=c("P1", "P2", "P3", "P4"))
```
#### Eucledian distance
```{r}
d.euc <- dist(df, method="euclidean", diag=T)
d.euc
```
#### Manhattan distance
```{r}
d.man <- dist(df, method="manhattan", diag=T)
d.man
```
#### Supremum distance
```{r}
d.sup <- dist(df, method="maximum", diag=T)
d.sup
```
#### Now, let's standardize the X and Y vectors.  scale() allows you to only center or Z-scale it (mean of 0 and std. dev. of 1)
```{r}
X.scale <- scale(df$X)
Y.scale <- scale(df$Y)
df.scale <- data.frame(X=X.scale, Y=Y.scale)
plot(df.scale, bg="lightgreen", pch=21, main="Plot with scaled data", xlim=c(-0.7, 1.51))
text(X.scale, Y.scale, pos=4, labels=c("P1", "P2", "P3", "P4"))
```
#### And what do the distances look like?
#### Manhattan distance
```{r}
d.man.scale <- dist(df.scale, method="manhattan", diag=T)
d.man.scale
d.man
```
### And so on ...
